language: objective-c
osx_image: xcode7.2
cache:
  - cocoapods
env:
  global:
  - WORKSPACE="RealmS.xcworkspace"
  - PROJECT="RealmS.xcodeproj"
  - IOS_SCHEME="RealmS"
  - IOS_SDK="iphonesimulator9.2"
  - CONFIGURATION="ReleaseTest"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 6 Plus"   SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6s Plus"  SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK"  POD_LINT="YES"
before_install:
  - set -o pipefail
  - brew install xctool
  - pod install
script:
  # Build Framework in Debug and Run Tests if specified
  - xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration Debug test
  # Build Framework in ReleaseTest and Run Tests if specified
  - xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration ReleaseTest test
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick
    fi
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
