language: objective-c
osx_image: xcode7.2
env:
  global:
  - WORKSPACE="RealmS.xcworkspace"
  - IOS_SCHEME="RealmS"
  - IOS_SDK="iphonesimulator9.2"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    # - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    # - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    # - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    # - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    # - DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - rvm use system
  - sudo gem install cocoapods -v '0.39.0'
  - sudo gem install xcpretty -v '0.2.2'
	- set -o pipefail
  - pod install
script:
  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  # Build Framework in ReleaseTest and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration ReleaseTest ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
