language: objective-c
osx_image: xcode7.2
cache:
  - cocoapods
env:
  global:
  - WORKSPACE="RealmS.xcworkspace"
  - PROJECT="RealmS.xcodeproj"
  - IOS_SCHEME="RealmS"
  - IOS_SDK="iphonesimulator9.2"
  - CONFIGURATION="ReleaseTest"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 5S"          SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - set -o pipefail
  - brew install xctool
  - pip install codecov
  - pod install
script:
  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration Debug test
    else
      xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration Debug build
    fi
  # Build Framework in ReleaseTest and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration ReleaseTest test
    else
      xctool -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration ReleaseTest build
    fi
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
notifications:
  email: false
after_success:
  - codecov
